### PR TITLE
Bump ICU_jll to v74.1

### PR DESCRIPTION
**Pull request by qwjyh**

### CODE REVIEW

**Comment by qwjyh** [comment]
ICU_jll is not compatible with Julia < 1.6.
https://github.com/JuliaBinaryWrappers/ICU_jll.jl/blob/3977c6ab0fadcaf18a3c83f5734cdb3da297faab/Project.toml

**Comment by qwjyh** [comment]
This package may need to drop support for Julia < 1.5.

**Comment by qwjyh** [comment]
Using Pkg, ICU_jll version can be obtained and this method seems to work.
```diff
diff --git a/src/StrICU.jl b/src/StrICU.jl
index e89ae6c..8634452 100644
--- a/src/StrICU.jl
+++ b/src/StrICU.jl
@@ -12,8 +12,15 @@ using ModuleInterfaceTools

 using ICU_jll

-# for now, just leave this hardcoded, until I can see how to get the version from ICU_jll
-const suffix = "_74"
+using Pkg
+function get_icu_suffix()
+    for (_, v) in Pkg.dependencies()
+        if v.name == "ICU_jll"
+            return v.version.major
+        end
+    end
+end
+const suffix = "_$(get_icu_suffix())"
 const iculib = ICU_jll.libicuuc
 const iculibi18n = ICU_jll.libicui18n
```

**Comment by ScottPJones** [comment]
Thank you for your PR!
I have tagged a new version of StrICU with this change (and updating the tests to use 1.6 & 1.10), as v1.2.0.

**Pull request merged**
